### PR TITLE
basic symja

### PR DESCRIPTION
**Pull request by maxandersen**
this allows you to do `jbang symjajsh@axkr`  without changing anything else.

### CODE REVIEW

**Comment by axkr** [comment]
In cmd.exe I'm getting

```
C:\jbang-0.92.2\bin>jbang symjajsh@axkr
File '@C:\Users\dev\AppData\Local\Temp\jbang8080717266275010342.args' for 'jshell' is not found.
```

although the file is available on the file  system.
Do I have to clear a cache or something like that?

**Comment by axkr** [comment]
@maxandersen for Windows PowerShell can you recommend in your documentation, how to setup the execution policies?
-  https:/go.microsoft.com/fwlink/?LinkID=135170

**Comment by maxandersen** [comment]
hmm - not sure what is causing that to fail - @quintesse might know.

**Comment by maxandersen** [comment]
im a bit perplexed as its literally just generating a temporary file to use for jshell as arguments as windows can't handle long arguments. Since the file is created by jbang, jshell should also have access to it.

**Comment by maxandersen** [comment]
for what it is worth i can reproduce the issue so should be possible to figure out what is going on.

**Comment by maxandersen** [comment]
okey so issue is that the dependency chain of axkr is quite massive which will overrun command line when using under windows cmd.exe shell.

We'll see if we can be smarter in generating so jshell can have large classpath under windows but until then if can use gitbash or wsl2 then it should work?

**Comment by axkr** [comment]
The `appassembler-maven-plugin` had the same issue where the problem is used by using a `lib\*` folder:
https://github.com/axkr/symja_android_library/blob/c6c03936d8520dfcd8d96223a74d9dc0f351df59/symja_android_library/matheclipse-io/pom.xml#L171

**Comment by maxandersen** [comment]
I released a version of jbang that doesn't use @file with jshell but now jshell just exits silently.

I wish we could use lib/* trick but all the dependencies aren't assemblied in one place. will see what we can do.

Works great everywhere else unfortunately :/

**Comment by axkr** [comment]
> I released a version of jbang that doesn't use @file with jshell but now jshell just exits silently.

Just tested and it exits directly after opening it with `jbang symjajsh@axkr` as you described.

**Comment by maxandersen** [comment]
@axkr note, you should add `-i` to make it go into interactive mode (but it might not help as cmd.exe gives up due to the length of the classpath :/

**Comment by quintesse** [comment]
With the latest version you could try running it with PowerShell which has a larger command buffer.

**Comment by axkr** [comment]
> With the latest version you could try running it with PowerShell which has a larger command buffer.

Powershell also terminates quietly with or without the `-i` option .

**Pull request merged**
